language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install -qq gfortran libatlas-base-dev python-numpy python-scipy
install:
  - pip freeze
  - pip install -r requirements.pip --use-mirrors
  - pip install -r requirements-test.pip --use-mirrors
  - pip freeze
script:
  - id
  - whoami
  - uname -a
  - ls -ld /tmp
  - ls -ld /dev/shm
  - sudo chmod a+w /dev/shm
  - sudo chown `whoami` /dev/shm
  - ls -ld /dev/shm
  - celeryd --config=bamboo.config.celeryconfig_test -E -l DEBUG&
  - cd bamboo
  - nosetests
  - cd ..
services:
  - mongodb
notifications:
  irc: "irc.freenode.org#moditest"
