language: python
python:
  - "2.6"
before_install:
  - sudo apt-get update
  - sudo apt-get install gcc g77 python-dev atlas3-base-dev
install:
  - pip install numpy --use-mirrors
  - pip install -r requirements.pip --use-mirrors
script: nosetests
