language: python
python:
  - "2.6"
# command to install dependencies
install:
  - export BLAS=
  - export LAPACK=
  - export ATLAS=
  - pip install numpy --use-mirrors
  - pip install -r requirements.pip --use-mirrors
# command to run tests
script: nosetests
