language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install -qq gfortran libatlas-base-dev
install:
  - pip freeze
  - pip install numpy
  - pip install -r requirements.pip --use-mirrors
  - pip install -r requirements-test.pip --use-mirrors
  - pip freeze
script:
  - ls -ld /dev/shm
  - sudo chmod a+wt /dev/shm
  - ls -ld /dev/shm
  - ./celeryd/celeryd start
  - tail -f ./celeryd/celeryd.log&
  - cd bamboo
  - nosetests
  - cd ..
  - ./celeryd/celeryd stop
services:
  - mongodb
notifications:
  irc: "irc.freenode.org#moditest"
